# Generated by Django 4.2.3 on 2023-07-21 03:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskApp', '0004_alter_category_img_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 22, 3, 17, 34, 639873)),
        ),
        migrations.AlterField(
            model_name='task',
            name='file',
            field=models.FileField(blank=True, default='TaskFiles/task_default.png', upload_to='TaskFiles/'),
        ),
    ]
