# Generated by Django 4.2.3 on 2023-07-21 03:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskApp', '0005_alter_task_due_date_alter_task_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.ImageField(default='media/images/cat_default.png', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 22, 3, 28, 7, 725956)),
        ),
        migrations.AlterField(
            model_name='task',
            name='file',
            field=models.FileField(blank=True, default='media/TaskFiles/task_default.png', upload_to='TaskFiles/'),
        ),
    ]
