# Generated by Django 4.2.3 on 2023-07-21 05:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskApp', '0006_alter_category_img_alter_task_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.ImageField(default='cat_default.png', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 22, 5, 10, 51, 927582)),
        ),
    ]
