# Generated by Django 4.2.3 on 2023-07-21 05:18

import datetime
from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('TaskApp', '0007_alter_category_img_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.ImageField(default=pathlib.PurePosixPath('/home/hossein/MaktabSharif/HW-98/HW15/TaskManager/media/images/cat_default.png'), null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 22, 5, 18, 10, 421060)),
        ),
    ]
