# Generated by Django 4.2.3 on 2023-07-21 06:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskApp', '0011_alter_category_img_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.ImageField(default='statics/cat_default.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 22, 6, 7, 21, 361601)),
        ),
    ]
