# Generated by Django 4.2.3 on 2023-07-21 06:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskApp', '0014_alter_category_img_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 22, 6, 38, 55, 338737)),
        ),
        migrations.AlterField(
            model_name='task',
            name='file',
            field=models.FileField(default='/TaskFiles/task_default.png', upload_to='TaskFiles/'),
        ),
    ]
